# Generated by Django 4.1.7 on 2023-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('EMPNO', models.IntegerField(primary_key=True, serialize=False)),
                ('ENAME', models.CharField(max_length=20)),
                ('JOB', models.CharField(max_length=20)),
                ('MGR', models.IntegerField(max_length=5)),
                ('HIREDATE', models.DateField()),
                ('SAL', models.IntegerField(max_length=10)),
                ('COMM', models.IntegerField(max_length=5, null=True)),
                ('DEPTNO', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='dept',
            name='dname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dept',
            name='loc',
            field=models.CharField(max_length=20),
        ),
    ]
