# Generated by Django 4.1.7 on 2023-04-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emp_alter_dept_dname_alter_dept_loc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMP',
        ),
    ]
